services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - helpdesk

  # 1. ESTE SOBE PRIMEIRO
  service-discovery:
    container_name: 'service-discovery'
    build:
      context: ./service-discovery
      dockerfile: Dockerfile
    environment:
      - SPRING_APPLICATION_NAME=service-discovery
      - SERVER_PORT=8761
      - PROFILE_ACTIVE=default
      # ISSO AQUI RESOLVE O SEU ERRO: Desativa a busca pelo Config Server
      # para que o Eureka suba usando apenas o seu application.yml local.
      - SPRING_CLOUD_CONFIG_ENABLED=false
    ports:
      - "8761:8761"
    # O Docker monitora quando o Java do Eureka realmente ligou
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8761/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - helpdesk
      
  # 2. ESTE SÓ SOBE QUANDO O DISCOVERY ESTIVER PRONTO (HEALTHY)
  config-server:
    image: rivald/backend-expert-configs
    container_name: config-server
    environment:
      - SPRING_CLOUD_CONFIG_SERVER_GIT_URI=https://github.com/rivaldoDeveloper/backend-expert-configs
      - SPRING_CLOUD_CONFIG_SERVER_GIT_USERNAME=rivaldoDeveloper
      - SPRING_CLOUD_CONFIG_SERVER_GIT_PASSWORD=PASSWORD
      - SERVER_PORT=8888
      - PROFILE_ACTIVE=default
      # Avisamos ao Config Server onde o Eureka está na rede Docker
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-discovery:8761/eureka/
    ports:
      - "8888:8888"
    depends_on:
      service-discovery:
        condition: service_healthy
    networks:
      - helpdesk

networks:
  helpdesk:
    driver: bridge